// =====================================================================
// Build script — produces deploy output for BOTH Vercel and Netlify.
//   Vercel : .vercel/output  (Build Output API v3: one Node function + static files)
//   Netlify: netlify/functions/server.mjs  (+ /public served as static)
// Run by `npm run build`; both platforms call it automatically.
// =====================================================================
import { build } from 'esbuild'
import { readdirSync, readFileSync, writeFileSync, mkdirSync, cpSync, rmSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()

// 1) Embed the SQL migrations so the app can self-apply them at runtime.
const migDir = join(root, 'migrations')
const files = readdirSync(migDir).filter((f) => f.endsWith('.sql')).sort()
const migrations = files.map((f) => ({ name: f, sql: readFileSync(join(migDir, f), 'utf8') }))
mkdirSync(join(root, 'src/generated'), { recursive: true })
writeFileSync(
  join(root, 'src/generated/migrations.ts'),
  `// AUTO-GENERATED by scripts/build.mjs — do not edit.\nexport const MIGRATIONS: { name: string; sql: string }[] = ${JSON.stringify(migrations)}\n`
)
console.log(`Embedded ${migrations.length} migrations:`, files.join(', '))

const common = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  jsx: 'automatic',
  jsxImportSource: 'hono/jsx',
  external: ['bufferutil', 'utf-8-validate'],
  // some bundled CommonJS deps call require(); give ESM output a real one
  banner: { js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
  logLevel: 'info'
}

// 2) Vercel — Build Output API
const vOut = join(root, '.vercel/output')
rmSync(vOut, { recursive: true, force: true })
const fnDir = join(vOut, 'functions/index.func')
mkdirSync(fnDir, { recursive: true })
await build({ ...common, entryPoints: [join(root, 'src/entry-vercel.ts')], outfile: join(fnDir, 'index.mjs') })
writeFileSync(
  join(fnDir, '.vc-config.json'),
  JSON.stringify({ runtime: 'nodejs22.x', handler: 'index.mjs', launcherType: 'Nodejs', shouldAddHelpers: false, maxDuration: 30 }, null, 2)
)
if (existsSync(join(root, 'public'))) cpSync(join(root, 'public'), join(vOut, 'static'), { recursive: true })
writeFileSync(
  join(vOut, 'config.json'),
  JSON.stringify({ version: 3, routes: [{ handle: 'filesystem' }, { src: '/(.*)', dest: '/index' }] }, null, 2)
)

// 3) Netlify — function in netlify/functions
const nDir = join(root, 'netlify/functions')
rmSync(nDir, { recursive: true, force: true })
mkdirSync(nDir, { recursive: true })
await build({ ...common, entryPoints: [join(root, 'src/entry-netlify.ts')], outfile: join(nDir, 'server.mjs') })

console.log('Build complete (Vercel + Netlify outputs).')
